#!/usr/bin/env python3
"""
ContextClimate data pipeline: Total Solar Irradiance (TSI) composite.

Source: LASP LISIRD, NRLTSI2 model composite (dataset id nrl2_tsi_P1M),
served via the LaTiS API as CSV. Free, no key, no CORS restriction on the
raw CSV endpoint (this script fetches server-side, so CORS is moot anyway).

Run this once to seed public/data/solar-tsi-monthly.json, then again on a
schedule (monthly is plenty -- the record only gets one new point a month)
via GitHub Actions. Matches the existing sunspot/ENSO/SST pipeline pattern:
self-hosted JSON in public/, generated by a small script, refreshed by CI.

Usage:
    python3 fetch_tsi.py [output_path]
"""
import csv
import io
import json
import sys
import urllib.request
from datetime import date, timedelta

EPOCH = date(1610, 1, 1)

MONTHLY_URL = "https://lasp.colorado.edu/lisird/latis/dap/nrl2_tsi_P1M.csv"
# Preliminary / near-real-time products -- may lag or be empty if the
# instrument feed has a gap. Checked in order; first one with rows wins.
# These report DAILY or 6-hourly, a finer resolution than the monthly
# composite -- see monthly_bin() below, which is why that matters.
RECENT_CANDIDATES = [
    "https://lasp.colorado.edu/lisird/latis/dap/nnl_tsi_prelim_P1D.csv",
    "https://lasp.colorado.edu/lisird/latis/dap/tsis_tsi_24hr.csv",
]

# Solar cycle start dates (approximate minima), widely cited (NOAA SWPC / SILSO).
# Update this list if a new cycle boundary is announced.
CYCLE_STARTS = [
    (20, date(1964, 10, 1)),
    (21, date(1976, 6, 1)),
    (22, date(1986, 9, 1)),
    (23, date(1996, 5, 1)),
    (24, date(2008, 12, 1)),
    (25, date(2019, 12, 1)),
]


def cycle_for(d: date) -> int:
    cyc = CYCLE_STARTS[0][0]
    for num, start in CYCLE_STARTS:
        if d >= start:
            cyc = num
    return cyc


def fetch_csv(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "contextclimate-pipeline/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("iso-8859-1")


def parse_days_since_epoch(csv_text: str):
    """Parses LaTiS CSV with 'time (days since 1610-01-01)' as first column."""
    reader = csv.reader(io.StringIO(csv_text))
    rows = []
    header_seen = False
    for row in reader:
        if not row:
            continue
        if row[0].startswith("time ("):
            header_seen = True
            continue
        if not header_seen or len(row) < 2:
            continue
        try:
            t = float(row[0])
            irr = float(row[1])
        except ValueError:
            continue
        if irr <= 0:
            continue  # LaTiS fill-value rows for missing days
        d = EPOCH + timedelta(days=t)
        rows.append((d, round(irr, 3)))
    return rows


def parse_julian_date(csv_text: str):
    """Parses LaTiS CSV with 'time (Julian Date)' as first column (tsis_tsi_*)."""
    reader = csv.reader(io.StringIO(csv_text))
    rows = []
    header_seen = False
    for row in reader:
        if not row:
            continue
        if row[0].startswith("time ("):
            header_seen = True
            continue
        if not header_seen or len(row) < 2:
            continue
        try:
            jd = float(row[0])
            tsi = float(row[1])
        except ValueError:
            continue
        if tsi <= 0:
            continue
        # JD 2451544.5 = 2000-01-01 00:00 UT
        d = date(2000, 1, 1) + timedelta(days=jd - 2451544.5)
        rows.append((d, round(tsi, 3)))
    return rows


def monthly_bin(rows):
    """Collapse (date, value) rows sharing a calendar month into a single
    averaged point, using the 15th as a stable representative day (matching
    the source composite's own convention for its monthly product).

    The "recent" near-real-time feeds report daily or 6-hourly, a much
    finer cadence than the monthly composite. Appending those rows to the
    monthly series unbinned makes the tail of the record look noisy (daily
    TSI swings a few W/m^2 with sunspot transits in a way the monthly mean
    smooths out) and it skews any simple average of "points" toward
    whichever stretch happens to have the most rows. Binning first keeps
    the whole series at a uniform monthly cadence.
    """
    buckets = {}
    order = []
    for d, v in rows:
        key = (d.year, d.month)
        if key not in buckets:
            buckets[key] = []
            order.append(key)
        buckets[key].append(v)
    out = []
    for (y, m) in order:
        vals = buckets[(y, m)]
        out.append((date(y, m, 15), round(sum(vals) / len(vals), 3)))
    return out


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "solar-tsi-monthly.json"

    monthly_csv = fetch_csv(MONTHLY_URL)
    monthly = parse_days_since_epoch(monthly_csv)
    if not monthly:
        print("ERROR: no monthly TSI rows parsed -- aborting, not overwriting output.", file=sys.stderr)
        sys.exit(1)

    # Try to append anything more recent than the monthly composite's last point.
    latest_monthly_date = monthly[-1][0]
    extra_recent = []
    for url in RECENT_CANDIDATES:
        try:
            recent = parse_julian_date(fetch_csv(url))
        except Exception as e:
            print(f"  (recent-feed check failed for {url}: {e})", file=sys.stderr)
            continue
        recent = [(d, v) for d, v in recent if d > latest_monthly_date]
        if recent:
            extra_recent = monthly_bin(recent)
            print(f"  found {len(recent)} more-recent rows from {url} -> {len(extra_recent)} monthly point(s) after binning")
            break

    points = [{"date": d.isoformat(), "tsi": v, "cycle": cycle_for(d)} for d, v in monthly]
    points += [{"date": d.isoformat(), "tsi": v, "cycle": cycle_for(d)} for d, v in extra_recent]
    points.sort(key=lambda p: p["date"])

    payload = {
        "source": "LASP LISIRD nrl2_tsi (NRLTSI2 model composite, monthly)",
        "units": "W/m^2",
        "generated": date.today().isoformat(),
        "latest_date": points[-1]["date"],
        "note": (
            "Monthly composite total solar irradiance at 1 AU. Points past the "
            "official monthly composite's cutoff are a monthly average of the "
            "near-real-time daily feed, so the whole series stays one point per "
            "calendar month. If latest_date lags today by more than ~6 weeks, "
            "LASP's near-real-time feed likely has a gap -- the tool should label "
            "the reading as 'latest available' rather than 'live'."
        ),
        "points": points,
    }

    with open(out_path, "w") as f:
        json.dump(payload, f, indent=0)

    print(f"Wrote {len(points)} points ({points[0]['date']} to {points[-1]['date']}) to {out_path}")


if __name__ == "__main__":
    main()
